###################
# STAGE 1: builder
###################

# Build currently doesn't work on > Java 11 (i18n utils are busted) so build on 8 until we fix this
FROM debian:stable-slim as builder

WORKDIR /app/source

ENV PATH="$PATH:/opt/conda/bin:/opt/conda/envs/venv/bin"
ENV FC_LANG en-US
ENV LC_CTYPE en_US.UTF-8

# bash:    various shell scripts
# wget:    installing lein
# git:     ./bin/version
# make:    backend building
# gettext: translations
RUN apt-get update && apt-get install -y coreutils bash git wget make gettext

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py37_22.11.1-1-Linux-x86_64.sh -O miniconda.sh && bash miniconda.sh -b -p /opt/conda
RUN /opt/conda/bin/conda install -c conda-forge -c bioconda -c anaconda mamba conda-pack

RUN /opt/conda/bin/mamba create -n venv -c bioconda -c conda-forge -y python=3.9 bedtools==v2.27.1 fastqc==0.11.8 multiqc==v1.8 fastq_screen==0.12.0 qualimap==2.0.0 vbt==v1.1

# Customized softewares
ADD ./resources/requirements.txt /data/requirements.txt
ADD ./bin/quartet-rseqc-report /opt/conda/envs/venv/bin/quartet-dseqc-report
RUN /opt/conda/envs/venv/bin/pip install -r /data/requirements.txt
ADD ./build/sentieon-genomics-201911.tar.gz /data/sentieon-genomics-201911.tar.gz
RUN tar xzvf /data/sentieon-genomics-201911.tar.gz
RUN mv /data/sentieon-genomics-201911 /sentieon-genomics

# Build quartet-rseqc-report.jar
# add the rest of the source
ADD . .

# lein: backend dependencies and building
ADD ./bin/lein /usr/local/bin/lein
RUN chmod 744 /usr/local/bin/lein

# install dependencies before adding the rest of the source to maximize caching
# backend dependencies
ADD project.clj .
RUN lein deps

# build the app
RUN lein uberjar

# Pack the conda environment
RUN conda-pack -n venv -o /tmp/env.tar && \
  mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
  rm /tmp/env.tar

RUN /venv/bin/conda-unpack

# ###################
# # STAGE 2: runner
# ###################

FROM debian:stable-slim as runner

ENV PATH="$PATH:/venv/bin:/venv/sentieon-genomics/bin"
ENV PYTHONDONTWRITEBYTECODE=1
ENV FC_LANG en-US
ENV LC_CTYPE en_US.UTF-8

RUN apt-get update && apt-get install -y coreutils bash git wget

WORKDIR /data

# Customized
COPY --from=builder /venv /venv
COPY --from=builder /app/source/target/uberjar/quartet-dseqc-report*.jar /quartet-dseqc-report.jar
COPY --from=builder /sentieon-genomics /venv/sentieon-genomics
