
#################################################################
# MultiQC Defaults
#################################################################
# If you want to change any of these config options, create a new
# file in any of the following locations:
#  1. <installation_dir>/multiqc_config.yaml (not pip or conda)
#  2. ~/.multiqc_config.yaml
#  3. <working directory>/multiqc_config.yaml
#################################################################

run_modules:
    - data_generation_information
    - pre_alignment_qc
    - post_alignment_qc
    - variant_calling_qc
    - supplementary

skip_generalstats: true